name: sistem_kejadian_awal_mobile
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^8.1.2
  # Paket yang kita butuhkan
  http: ^1.2.1
  dio: ^5.4.3+1
  shared_preferences: ^2.2.3
  provider: ^6.1.2
  image_picker: ^1.0.7
  intl: ^0.18.1
  cupertino_icons: ^1.0.8

  # Paket untuk Peta dan Lokasi
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  geolocator: ^12.0.0
  pdf: ^3.10.8
  printing: ^5.11.1

  flutter_native_splash: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1 # Paket ikon aplikasi

flutter:
  uses-material-design: true
  assets:
    - assets/images/

# --- KONFIGURASI SPLASH SCREEN ---
flutter_native_splash:
  color: "#F0F2F5"
  image: assets/images/app_icon.png
  android_gravity: center
  ios_content_mode: scaleAspectFit

  android_12:
    image: assets/images/app_icon.png
    icon_background_color: "#F0F2F5"

# --- KONFIGURASI ICON APLIKASI ---
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/icon_SIKAP.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/icon_SIKAP.png"
  min_sdk_android: 21
